# Generated by Django 6.0.5 on 2026-06-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='frequency',
            field=models.CharField(blank=True, choices=[('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual'), ('YEARLY', 'Anual')], max_length=10, null=True, verbose_name='Frecuencia de recurrencia'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_recurrent',
            field=models.BooleanField(default=False, verbose_name='¿Es reserva recurrente?'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='recurrence_count',
            field=models.PositiveIntegerField(default=1, help_text='Indica cuántas temporadas/ciclos se va a repetir esta reserva (incluyendo la primera).', verbose_name='Número de repeticiones totales'),
        ),
    ]
