# Generated by Django 6.0.5 on 2026-05-26 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propieties', '0004_propiedad_imagen_principal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenpropiedad',
            options={'verbose_name': 'Imagen de Propiedad', 'verbose_name_plural': 'Imágenes de Propiedads'},
        ),
    ]
